# -*- coding: utf-8 -*-
"""dorduncuDers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXaSHOdWzTT2CHqr6M0G4sctajKZzYEp
"""

## We will talk about exception handling!
x=1
assert x == 2     ##Assertion eror!
##başka eror: divison by 0 eror vb.

## Error Handling, Exception Handling is done by means of try and except blocks
x=5
y=0
try:
  x/y ##should give division by 0 eror
except Exception:
  ##Do whatever you like here.
  print("Hey you are doing 0 division.")
  ##the codes jumps to this exception.

x=4
y=0
try:
  x/y
except ZeroDivisionError:
  print("aaaaaaaa")
except OSError:
  print("hımm")
finally:
  print("I am the final boss, im always here.")

L=[0,1]
try:
  L[3]=2
except Exception as E:         ##as E allows you to pick the type of the error!
  print(f"There is an eror. The error is {E}")

##A toy example
import numpy as np
A=list(np.random.rand(1000))
##For now, lets assume that we dont know the size of this list
##How do we find out the length of this list by means of try except blocks?
##len(A)  ofc
def leen_(A:list)->int:
  i=0
  while True:
    try:
      A[i]
      i+=1
    except Exception:
      break
  return i

leen_(A)   ##Anlamıyorum i+=2 yapınca da 1000 diyor
##ama 3 diyince değişiyor

### Let's read some files and write some files!!
###Task given a string, open a txt file and write this string to the txt file and save it.
name_of_file ="file.txt"
with open(name_of_file, "a") as file:
  file.write("Hello hardware, whats up")

  ##it creates this file.txt buy itself (jupyterde kendisi yaptı)

name_of_file ="file.name_of_file ="file.txt"  ##i dont get it
with open(name_of_file, "a") as file:
  file.write("Hello hardware, whats up")txt"
with open(name_of_file, "a") as file:   ## a stands for : append
  file.write("I am good how are you?")

## a: append w: write
name_of_file ="file.txt"
with open(name_of_file, "r") as file:
  inside file.read()
  ##wtf hocayla aynısını yazıyroum bende hata veriyor

sh=open("shakespeare.txt","r")
sh.readlines()   ##yes i dont get it hocada no eror?
sh.readline()
sh.close()

name_of_file ="shakespeare.txt"
with open(name_of_file,"a") as file:
  inside=file.read()

inside

##Hoe do we create (initiate) objects in python?
##This usually happens by means of classes
def f(x):
  pass

a=[] ## initiate

b=(2,3)

isinstance(b,tuple)       ##what does this do i dont get it

class car:
  brand="A"

CAR = car()

car.brand

dir(CAR)

class car:
  def __init__(self,brand,power,color):
    self.brand=brand
    self.power=power  ##attributes
    self.color=color
  def return_brand(self):       ##method of your object
    return self.brand

CAR=car("Toyota",10,"red")

CAR.return_brand()

##hocanın notlarından ya da ders kaydından bak bruaya

##python inheritance filan yaptı. patikada yoksa youtube dan izle!

##Let's create a class of coins with some methods
##attributes: p the probability that you get tails
##methods: flit it once, or maybe more than once
class coin:
  def__init__(self,p):
    assert 0<=p<=1, "p is a probability value"
    self.p=p
  def flip(self):
    self.c=["h","t"]