# -*- coding: utf-8 -*-
"""KOPYAKOPYA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXx7uksysLifHaBqhu68r75lYbA5fJr-

## Follow the instructions, and write your codes in the right cells.
[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/y-akbal/Tedu_Python_for_DS/blob/main/ALE/ADA440-ALE4.ipynb)
"""

#### Run this cell as this cell will download some necessary files for your exercises.
### Run the following function, do not change any line of it.
import requests
def download_text():
    data_url1 = 'https://raw.githubusercontent.com/y-akbal/Tedu_Python_for_DS/main/data/USvideos.csv'
    "Data_Visualizations/Dynamic_Visuals_Using_Date_Range_Slicers_Pt1/data/USvideos.csv"
    text1 = requests.get(data_url1)
    with open("USvideos.csv","a") as file:
        file.write(text1.text)
try:
    text = download_text()
    print("Text downloaded succesfully!! the name of the file is USvideos.csv")
except Exception as a:
  print(f"Something went wrong body that is: {a}")

## Import pandas
##
## Your code here
import pandas as pd

## Read the youtube dataset ("USvideos.csv")
##
## Your code here

import pandas as pd
datas = pd.read_csv("USvideos.csv")

##print(datas.head())
print(datas)

## Inspect the dataset, delete the following columns
## a) video_id
## b) thumbnail_link
## c) publish_time
## d) channel_title
## e) title
## f) omments_disabled, ratings_disabled

import pandas as pd
datas = pd.read_csv("USvideos.csv")

deleting = ['video_id', 'thumbnail_link', 'publish_time', 'channel_title', 'title', 'comments_disabled', 'ratings_disabled']
datas = datas.drop(deleting, axis=1)

print(datas.head())

## Are there any missing values in your dataset?
##
## Your code here

import pandas as pd
datas = pd.read_csv("USvideos.csv")

missing = datas.isnull().sum()

print(missing)

## What is the average number of likes?
##
## Your code here
import pandas as pd
datas = pd.read_csv("USvideos.csv")

datas['likes'] = pd.to_numeric(datas['likes'], errors='coerce')

avg_likes = datas['likes'].mean()

print("Average number of likes:", avg_likes)

## What is the average number of dislikes?
## Your code here

import pandas as pd
datas = pd.read_csv("USvideos.csv")

datas['dislikes'] = pd.to_numeric(datas['dislikes'], errors='coerce')


avg_dislikes = datas['dislikes'].mean()

print("Average number of dislikes:", avg_dislikes)

## What is the title of the video that has the highest views?
##
## Your code here
import pandas as pd
datas = pd.read_csv("USvideos.csv")


if datas['views'].dtype != 'int64' and datas['views'].dtype != 'float64':

    datas['views'] = pd.to_numeric(datas['views'], errors='coerce')


index_of = datas['views'].idxmax()
title_of_video = datas.loc[index_of, 'title']


print("Title of the video with the highest views:", title_of_video)

## What is average number of comments in each category with respect to category_id?
##
## Your code here
import pandas as pd
datas = pd.read_csv("USvideos.csv")



datas['comment_count'] = pd.to_numeric(datas['comment_count'], errors='coerce')

average_comments = datas.groupby('category_id')['comment_count'].mean()

print(average_comments)

## How many videos are there in each category?
##
## Your code here
import pandas as pd
datas = pd.read_csv("USvideos.csv")

cate = datas['category_id'].value_counts()

print(cate)

## What is the title of the video that has the largest number of tags?
##
## Your code here

import pandas as pd
datas = pd.read_csv("USvideos.csv")

datas['tags_length'] = datas['tags'].str.split('|').apply(lambda x: len(x))


max_tags = datas[datas['tags_length'] == datas['tags_length'].max()]['title'].values[0]

print("Title of the video with the largest number of tags:", max_tags)

