# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wg_2t3nrUZn8aSh4tkipA2YPqdeEWFgi
"""

import numpy as np

def hoppa(L):
    a = -np.inf
    place = 0
    for i, j in enumerate(L):
        if j > a:
            a = j
            place = i
    return a, place

L=[1,4,4,9,9,7,2,7,9,3,9,3]

hoppa(L)

class BankAccount:
  def __init__(self):
    self.balance=0
  def withdraw(self,amount):
    self.balance-=amount
    return self.balance
  def deposit(self,amount):
    self.balance+=amount
    return self.balance

class CustomerAccount(BankAccount):
  def __init__(self,balance):
    self.balance=balance
  def withdraw(self,amount):
    if self.balance<amount:
      print("Not enough balance!!!")
    else:
      return super().withdraw(amount)

